title: Zelong Guo
url: "https://zelongguo.github.io/"
baseurl: ""

markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

tracking_id: G-2GDVTVFMCF

sass:
    style: compressed
    sass_dir: _sass
